branches:
  only:
    - master

language: java

addons:
  sonarqube:
    token:
      secure: "BOEDSMd6XyHxGQRBeM4XWpL3NDEur5gspkRubVkbFf+m2y4ON4Y9AM7cjlAn6W67IVdyCd6bwBuQwS/ExfglIsTFPVpuSMbTqu3nUtajllFRIIb/4xdeK6bGqJWxobOzoag86+nfrxlQb5XFOXFwi9ZFZgSYM7aANGyE/OXXL8A="

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.sonar/cache
  
matrix:
  include:
    - jdk: "oraclejdk8"
      env: BUILD_SITE=true MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz"
    - jdk: "openjdk7"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz"
    - jdk: "openjdk7"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz"
    - jdk: "openjdk7"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz"
    - jdk: "openjdk7"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz"
    - jdk: "oraclejdk7"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz"
    - jdk: "oraclejdk7"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz"
    - jdk: "oraclejdk7"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz"
    - jdk: "oraclejdk7"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.tar.gz"
    - jdk: "oraclejdk8"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz"
    - jdk: "oraclejdk8"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.1.1/binaries/apache-maven-3.1.1-bin.tar.gz"
    - jdk: "oraclejdk8"
      env: BUILD_SITE=false MAVEN_URL="http://archive.apache.org/dist/maven/maven-3/3.2.5/binaries/apache-maven-3.2.5-bin.tar.gz"

before_install:
  - wget $MAVEN_URL --output-document=maven.tar.gz
  - wget https://github.com/casperjs/phantomjs-builds/archive/v1.8.2.tar.gz -O phantomjs-1.8.2.tar.gz
  - wget https://github.com/casperjs/phantomjs-builds/archive/v1.9.8.tar.gz -O phantomjs-1.9.8.tar.gz
  - wget https://github.com/casperjs/casperjs/archive/1.0.4.tar.gz -O casperjs-1.0.4.tar.gz
  - wget https://github.com/casperjs/casperjs/archive/1.1.3.tar.gz -O casperjs-1.1.3.tar.gz

install:
  - mkdir maven && tar --strip-components=1 -zxf maven.tar.gz -C maven
  - tar zxf phantomjs-1.8.2.tar.gz
  - tar zxf phantomjs-1.9.8.tar.gz
  - tar zxf casperjs-1.0.4.tar.gz
  - tar zxf casperjs-1.1.3.tar.gz

before_script:
  - export PATH=$(pwd)/casperjs-1.1.3/bin:$(pwd)/phantomjs-builds-1.9.8/bin:$(pwd)/maven/bin:$PATH
  - echo "export M2_HOME=$(pwd)/maven" > ~/.mavenrc
  - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
          <toolchains>
            <toolchain>
              <type>casperjs</type>
              <provides> <version>1.0.4</version> </provides>
              <configuration><casperjsExecutable>$(pwd)/casperjs-1.0.4/bin/casperjs</casperjsExecutable></configuration>
            </toolchain>
            <toolchain>
              <type>casperjs</type>
              <provides> <version>1.1.3</version> </provides>
              <configuration><casperjsExecutable>$(pwd)/casperjs-1.1.3/bin/casperjs</casperjsExecutable></configuration>
            </toolchain>
          </toolchains>" > ~/.m2/toolchains.xml
  - sed -e "/<settings>/ a\
            <servers>\
              <server>\
                <id>github</id>\
                <password>\${env.GITHUB_OAUTH}</password>\
              </server>\
            </servers>\
          " -e "/<profiles>/ a\
              <profile>\
                <id>casperjs</id>\
                <activation>\
                  <activeByDefault>true</activeByDefault>\
                </activation>\
                <properties>\
                  <casperjs-default-path>$(pwd)/casperjs-1.1.3/bin</casperjs-default-path>\
                  <phantomjs-for-casper-1.0-path>$(pwd)/phantomjs-builds-1.8.2/bin</phantomjs-for-casper-1.0-path>\
                  <phantomjs-for-casper-1.1-path>$(pwd)/phantomjs-builds-1.9.8/bin</phantomjs-for-casper-1.1-path>\
                </properties>\
              </profile>\
          " -i ~/.m2/settings.xml

script:
  - java -version
  - mvn -version
  - phantomjs --version
  - casperjs --version
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${BUILD_SITE}" = "true" ]; then mvn -Pit,sonar clean install sonar:sonar -Dinvoker.streamLogs=true ; else mvn -Pit install -Dinvoker.streamLogs=true ; fi
  - if [ "${TRAVIS_PULL_REQUEST}" = "false" -a "${BUILD_SITE}" = "true" ]; then travis_wait mvn -Psite site-deploy ; fi

